# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

use_frameworks!
workspace 'ChatOfMiddleEarth'

target 'ChatOfMiddleEarth' do
  # Comment the next line if you don't want to use dynamic frameworks
  pod 'SnapKit'
  pod 'IQKeyboardManagerSwift'
  # Pods for BizinGold

end
